[package]
name = "sandbox-bin"
version = "0.1.0"
authors = ["Lancern <msrlancern@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"error-chain" = "0.12"
"sandbox" = { path = "../sandbox" }
"clap" = "2.33"
