[package]
name = "builtin_languages"
version = "0.1.0"
authors = ["Lancern <msrlancern@126.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
"log" = "0.4"
"serde" = { version = "1.0", features = ["derive"] }
"serde_yaml" = "0.8"
"judge" = { path = "../judge" }
